import { Inter } from "next/font/google";
import "./globals.css";
import GlobalState from "./context";
import Navbar from './components/Navbar'

const inter = Inter({ subsets: ['latin']})

export const metadata = {
  title: "Create Next App",
  description: 'Generated by create next app',
}
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <GlobalState>
          <Navbar/>
          <main className="pt-0 mt-0 flex min-h-screen flex-col">{children}</main>
        </GlobalState>
        </body>
    </html>
  );
}
